export const PROJECT_CONTROL_PAGES = [
  "/project-control",
  "/project-control/contractors",
  "/project-control/trades",
  "/project-control/estimating",
  "/project-control/bid-packages",
  "/project-control/code-compliance",
  "/project-control/permitting",
  "/project-control/incentives",
  "/project-control/rag-knowledge",
  "/project-control/mcp-tools",
  "/project-control/agents",
  "/project-control/templates",
  "/project-control/risks",
  "/project-control/decisions",
  "/project-control/rwa",
  "/project-control/xrpl-readiness",
  "/project-control/pof",
  "/project-control/incentive-intelligence",
  "/project-control/esg-scorecard",
  "/project-control/funding-match",
  "/project-control/evidence-intake",
  "/project-control/rag-index",
  "/project-control/lender-packet",
  "/project-control/incentive-evidence",
  "/project-control/submission-readiness",
] as const;
